server:
  port: 8081
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/cinelumi
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql